name: Polybot Build Dev

on:
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker_build.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Image
        id: docker_build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          IMAGE_NAME=${DOCKER_USERNAME}/polybot-dev:${{ github.run_number }}
          echo "✅ Built image: $IMAGE_NAME"
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Debug built image name
        run: |
         echo "✅ This is the image output: ${{ steps.docker_build.outputs.image }}"
      

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    secrets:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        TELEGRAM_BOT_TOKEN_DEV: ${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}
        TELEGRAM_APP_URL_DEV: ${{ secrets.TELEGRAM_APP_URL_DEV }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # ✅ ADD THIS LINE